<?php
// if (!defined('WHATSAPP_TITLE')) define('WHATSAPP_TITLE', 'WHATSAPP HELP');

// if (!defined('LOCATION_TITLE')) define('LOCATION_TITLE', 'LOCATIONS');
// if (!defined('BRIMINGHAM_LOCATION_TITLE')) define('BRIMINGHAM_LOCATION_TITLE', 'Birmingham Details');
// if (!defined('LONDON_LOCATION_TITLE')) define('LONDON_LOCATION_TITLE', 'London Details');

// if (!defined('MY_ACCOUNT_TITLE')) define('MY_ACCOUNT_TITLE', 'MY ACCOUNT');
// if (!defined('MY_ACCOUNT_LOGIN')) define('MY_ACCOUNT_LOGIN', 'LOGIN');
// if (!defined('MY_WISHLIST_TITLE')) define('MY_WISHLIST_TITLE', 'MY WISHLIST');
// if (!defined('MY_CART_TITLE')) define('MY_CART_TITLE', 'MY CART');
// if (!defined('MY_CURRENCY_SYMBOL')) define('MY_CURRENCY_SYMBOL', '£');

// // Bespoke Diamond Search Constants

// /*
// ** Tooltips
// */
// if (!defined('CARAT_TOOLTIP')) define('CARAT_TOOLTIP', 'THIS IS THE WEIGHT OF THE CENTRAL MAIN STONE OF YOUR ENGAGEMENT RING.ONE CARAT IS EQUAL TO 1/5 OF A GRAM MAKING DIAMONDS THE MOST EXPENSIVE MINERAL FOUND ON EARTH.');
// if (!defined('COLOUR_TOOLTIP')) define('COLOUR_TOOLTIP', 'SCALE REFLECTS NO PRESENCE OF COLOUR (D-F) BEING THE BEST, TINY HINT OF COLOUR (G-I) AND "WHITISH LOOKING" COLOURS (J-K). L-Z COLOURS ON GIA GRADING WILL SHOW SOME COLOUR IN THE DIAMOND TO THE NAKED EYE.');
// if (!defined('CLARITY_TOOLTIP')) define('CLARITY_TOOLTIP', 'SCALE SHOWS THE PRESENCE OF BLEMISHES OR MARKS IN OR ON THE DIAMOND, IF BEING ABSOLUTELY NO BLEMISHES AND SI2 BEING SOME BLEMISHES SEEN WITH THE NAKED EYE.');
// if (!defined('CUT_GRADE_TOOLTIP')) define('CUT_GRADE_TOOLTIP', 'SCALE SHOWS THE OVERALL BRILLIANCE AND LIGHT REFLECTION (SPARKLE FACTOR) OF A DIAMOND. HEARTS & ARROWS AND IDEAL (EXCELLENT CUT) BEING THE BEST AND GOOD BEING AVERAGE. CUT GRADES ARE ONLY SHOWN FOR ROUND BRILLIANT CUT DIAMONDS.');
// if (!defined('POLISH_TOOLTIP')) define('POLISH_TOOLTIP', 'SCALE REFLECTS THE FINISH OF THE DIAMOND. AN EXCELLENT POLISH MEANING THERE ARE NO EXTRA OR LESSER FACETS AND GIRDLE BEING POLISHED. AN EXCELLENT OR VERY GOOD HAVE SIMILAR PARAMETERS, GOOD BEING ABOVE AVERAGE.');
// if (!defined('SYMMETRY_TOOLTIP')) define('SYMMETRY_TOOLTIP', 'SCALE SHOWS THE OVERALL ANGLES AT WHICH THE DIAMOND IS CUT APPROPRIATE TO THE SHAPE OF THE DIAMOND. AN EXCELLENT OR VERY GOOD GRADE ARE ACCEPTABLE, GOOD BEING ABOVE AVERAGE.');
// if (!defined('FLUORESCENCE_TOOLTIP')) define('FLUORESCENCE_TOOLTIP', 'SHOWS THE PRESENCE OF UV LIGHT REFLECTION WITHIN THE DIAMOND. A STRONG GRADE MAY MAKE THE STONE HAZY OR MILKY. NONE, FAINT OR SLIGHT, AND AT TIMES, MEDIUM ARE ACCEPTABLE STANDARDS.');
// if (!defined('CERTIFICATE_TOOLTIP')) define('CERTIFICATE_TOOLTIP', 'THE LABORATORY THAT GRADES THE DIAMOND. WE STOCK ONLY THE BEST, GIA BEING THE FOREMOST FOLLOWED BY IGI AND HRD WHICH HAVE EQUALLY ACCEPTABLE STANDARDS OF GRADING.');

// if (!defined('APPIMAGEURL')) define('APPIMAGEURL', 'http://127.0.0.1:8000/');


return [
    'WHATSAPP_TITLE' => 'WHATSAPP HELP',

    'LOCATION_TITLE' => 'LOCATIONS',
    'BRIMINGHAM_LOCATION_TITLE' => 'Birmingham Details',
    'LONDON_LOCATION_TITLE' => 'London Details',

    'MY_ACCOUNT_TITLE'   => 'MY ACCOUNT',
    'MY_ACCOUNT_LOGIN'   => 'LOGIN',
    'MY_WISHLIST_TITLE'  => 'MY WISHLIST',
    'MY_CART_TITLE'      => 'MY CART',
    'MY_CURRENCY_SYMBOL' => '£',

    'CARAT_TOOLTIP'        => 'THIS IS THE WEIGHT OF THE CENTRAL MAIN STONE OF YOUR ENGAGEMENT RING.ONE CARAT IS EQUAL TO 1/5 OF A GRAM MAKING DIAMONDS THE MOST EXPENSIVE MINERAL FOUND ON EARTH.',
    'COLOUR_TOOLTIP'       => 'SCALE REFLECTS NO PRESENCE OF COLOUR (D-F) BEING THE BEST, TINY HINT OF COLOUR (G-I) AND "WHITISH LOOKING" COLOURS (J-K). L-Z COLOURS ON GIA GRADING WILL SHOW SOME COLOUR IN THE DIAMOND TO THE NAKED EYE.',
    'CLARITY_TOOLTIP'      => 'SCALE SHOWS THE PRESENCE OF BLEMISHES OR MARKS IN OR ON THE DIAMOND, IF BEING ABSOLUTELY NO BLEMISHES AND SI2 BEING SOME BLEMISHES SEEN WITH THE NAKED EYE.',
    'CUT_GRADE_TOOLTIP'    => 'SCALE SHOWS THE OVERALL BRILLIANCE AND LIGHT REFLECTION (SPARKLE FACTOR) OF A DIAMOND. HEARTS & ARROWS AND IDEAL (EXCELLENT CUT) BEING THE BEST AND GOOD BEING AVERAGE. CUT GRADES ARE ONLY SHOWN FOR ROUND BRILLIANT CUT DIAMONDS.',
    'POLISH_TOOLTIP'       => 'SCALE REFLECTS THE FINISH OF THE DIAMOND. AN EXCELLENT POLISH MEANING THERE ARE NO EXTRA OR LESSER FACETS AND GIRDLE BEING POLISHED. AN EXCELLENT OR VERY GOOD HAVE SIMILAR PARAMETERS, GOOD BEING ABOVE AVERAGE.',
    'SYMMETRY_TOOLTIP'     => 'SCALE SHOWS THE OVERALL ANGLES AT WHICH THE DIAMOND IS CUT APPROPRIATE TO THE SHAPE OF THE DIAMOND. AN EXCELLENT OR VERY GOOD GRADE ARE ACCEPTABLE, GOOD BEING ABOVE AVERAGE.',
    'FLUORESCENCE_TOOLTIP' => 'SHOWS THE PRESENCE OF UV LIGHT REFLECTION WITHIN THE DIAMOND. A STRONG GRADE MAY MAKE THE STONE HAZY OR MILKY. NONE, FAINT OR SLIGHT, AND AT TIMES, MEDIUM ARE ACCEPTABLE STANDARDS.',
    'CERTIFICATE_TOOLTIP'  => 'THE LABORATORY THAT GRADES THE DIAMOND. WE STOCK ONLY THE BEST, GIA BEING THE FOREMOST FOLLOWED BY IGI AND HRD WHICH HAVE EQUALLY ACCEPTABLE STANDARDS OF GRADING.',

    'APPIMAGEURL' => 'http://127.0.0.1:8000/',
];
